### ISSUE TITLE
No support for Jasmine v2

### ISSUE THREAD

**Issue by jsatk** [searls/jasmine-stealth#5]
Any plans to support Jasmine v2?

**Comment by caseyhoward** [comment]
Is this ever going to get done? Is there a new way to stub functions with arguments in jasmine2 that I don't know about?

**Comment by searls** [comment]
Short answer: no. Since this thread, I've developed testdouble.js which offers much better stub & spy support than jasmine stealth ever could have. Given the privatization of the Spy API under Jasmine 2, I think stealth is at a dead end.

Docs here: https://github.com/testdouble/testdouble.js

**Comment by caseyhoward** [comment]
Cool, thanks. I'll check that out. Upon first look, I'm not a big fan of having to clean up manually. That's why I have been avoiding sinon. I want something that hooks into the framework and knows to clean up.

I have something that works for stubbing arguments in jasmine2. Are there any other issues that would prevent jasmine-stealth from being compatible with jasmine2?

**Comment by searls** [comment]
The only cleanup you ought to do is:

```
afterEach(function(){ td.reset() })
```

Exactly one time in a spec helper (not once per test, once in your entire suite). I don't think that's overly onerous. And if you're not using the td.replace() API you don't really need to reset, necessarily. It's just an added protection against potential pollution.

**Comment by caseyhoward** [comment]
Yeah, if you only have to it once, that's fine with me.

Also, this a little hack I did to get stubbing arguments to work by using ".and.callFake". It doesn't add a method to the return value of jasmine.createSpy() like jasmine-stealth does since that's impossible. It's just it's function kind of like spyOn. It also doesn't support argument matchers.

I'm glad you made a new library that won't break the next time jasmine decides to change something. I still can't believe they don't have stubbing out a method with arguments built in, but that's a different issue. I'm going to give it a try since there's a bit more work I would need to do and I don't really care to do it if there's already a better solution :)
